#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
alias bst="ps -ef | grep ssh/socket | grep -v grep"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Use rg (https://github.com/BurntSushi/ripgrep) instead of the default find
# command for listing path candidates.
# - The first argument to the function is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
# - rg only lists files, so we use with-dir script to augment the output
_fzf_compgen_path() {
  rg --files "$1" | with-dir "$1"
}

# Use rg to generate the list for directory completion
_fzf_compgen_dir() {
  rg --files "$1" | only-dir "$1"
}
export FZF_CTRL_T_OPTS=" --preview '(highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'"

setopt interactivecomments

export DEFAULT_USER=dresnick

export POWERLEVEL9K_VIRTUALENV_BACKGROUND='springgreen4'
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(pyenv virtualenv aws kubecontext dir vcs vi_mode)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time status root_indicator background_jobs time)
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONFIG=minikube
# export POWERLEVEL9K_KUBECONTEXT_DEFAULT_NAMESPACE=default
export POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=false
# export POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_CONFIG=false
export POWERLEVEL9K_VI_INSERT_MODE_STRING="%B%F{1}❯%F{3}❯%F{2}❯%f%b"
export POWERLEVEL9K_VI_COMMAND_MODE_STRING="%B%F{2}❮%F{3}❮%F{1}❮%f%b"
